// lib/constant.dart

final Map<String, List<String>> categoryLogic = {
  "American": ["Steak", "Deli", "American", "Burger", "Diner"],
  "Bagels": ["Bagel", "Bakery", "Deli"],
  "Chinese": ["Chinese", "Asian", "Dim Sum"],
  "French": ["French", "Bistro"],
  "Indian": ["Indian"],
  "Italian": ["Pizza", "Italian", "Pasta"],
  "Japanese": ["Japanese", "Asian", "Sushi", "Omakase"],
  "Korean": ["Korean", "Asian", "BBQ"],
  "Mexican": ["Mexican", "Tacos"],
  "Middle Eastern": ["Middle Eastern", "Falafel"],
  "Thai": ["Thai", "Asian"],
};

final Map<String, String> categoryFlags = {
  // --- 🍔 FOOD ITEMS ---
  "Burger": "🍔",
  "Pizza": "🍕",
  "Sushi": "🍣",
  "Coffee": "☕",
  "Coffee Shop": "☕",
  "Coffe Shop": "☕",
  "Cafe": "☕",
  "Bakery": "🥐",
  "Bagel": "🥯",
  "Sandwich": "🥪",
  "Sandwicg": "🥪",
  "Salad": "🥗",
  "Soup": "🥣",
  "Breakfast": "🥞",
  "Breakfadst": "🥞",
  "Brunch": "🥂",
  "Deli": "🥒",
  "Steak": "🥩",
  "Steak House": "🥩",
  "Steakhouse": "🥩",
  "Seafood": "🦞",
  "Fish": "🐟",
  "Fish And Chips": "🇬🇧",
  "Oyster": "🦪",
  "Vegetarian": "🥦",
  "Vegan": "🥕",
  "Ice Cream": "🍦",
  "Dessert": "🍰",
  "Cake": "🎂",
  "Cookie": "🍪",
  "Cookies": "🍪",
  "Cookie Dough": "🍪",
  "Donut": "🍩",
  "Bar": "🍺",
  "Pub": "🍺",
  "Chicken": "🍗",
  "Fried Chicken": "🍗",
  "Wings": "🍗",
  "Ramen": "🍜",
  "Noodle": "🍜",
  "Rice": "🍚",
  "Tacos": "🌮",
  "Burrito": "🌯",
  "Quesadilla": "🧀",
  "Empanada": "🥟",
  "Bbq": "🍖",
  "Barbecue": "🍖",
  "Dim Sum": "🥟",
  "Dimsum": "🥟",
  "Dumpling": "🥟",
  "Hot Pot": "🍲",
  "Hotpot": "🍲",
  "Fast Food": "🍟",
  "Tea": "🍵",
  "Bubble Tea": "🧋",
  "Milk Tea": "🧋",
  "Juice": "🧃",
  "Smoothie": "🥤",
  "Acai": "🫐",
  "Açaí": "🫐",
  "Poke": "🥗",
  "Bowl": "🥗",
  "Kebab": "🍢",
  "Gyro": "🥙",
  "Falafel": "🧆",
  "Curry": "🍛",
  "Crepe": "🥞",
  "Pancake": "🥞",
  "Waffle": "🧇",
  "Fries": "🍟",
  "Hot Dog": "🌭",
  "Corn Dog": "🌭",
  "Pretzel": "🥨",
  "Macaroni And Cheese": "🧀",
  "Pasta": "🍝",
  "Sausage": "🌭",
  "Tapas": "🇪🇸",
  "Alcohol": "🍷",
  "Wine": "🍷",
  "Beer": "🍺",
  "Cocktail": "🍸",
  "Cocktails": "🍸",
  "Whiskey": "🥃",
  "Sake": "🍶",
  "Soju": "🍾",
  "Yogurt": "🍦",
  "Frozen Yogurt": "🍦",
  "Cacao": "🍫",
  "Chocolate": "🍫",
  "Cannabis": "🌿",
  "Churro": "🍩",
  "Charcuterie": "🧀",
  "Cheese": "🧀",
  "Fondue": "🫕",
  "Appetizer": "🍤",
  "Snack": "🍿",
  "Fruit": "🍎",
  "Omakase": "🍣",
  
  // --- 🌎 AMERICAS ---
  "American": "🇺🇸",
  "New American": "🇺🇸",
  "Californian": "🇺🇸",
  "Texan": "🤠",
  "Mexican": "🇲🇽",
  "Tex Mex": "🌮",
  "Brazilian": "🇧🇷",
  "Peruvian": "🇵🇪",
  "Argentinian": "🇦🇷",
  "Colombian": "🇨🇴",
  "Columbian": "🇨🇴",
  "Venezuelan": "🇻🇪",
  "Cuban": "🇨🇺",
  "Dominican": "🇩🇴",
  "Puerto Rican": "🇵🇷",
  "Jamaican": "🇯🇲",
  "Jerk": "🇯🇲",
  "Caribbean": "🌴",
  "Canadian": "🇨🇦",
  "Salvadoran": "🇸🇻",
  "Salvadorian": "🇸🇻",
  "Salvadorean": "🇸🇻",
  "Guatemalan": "🇬🇹",
  "Honduran": "🇭🇳",
  "Costa Rican": "🇨🇷",
  "Panamanian": "🇵🇦",
  "Ecuadorian": "🇪🇨",
  "Equadorian": "🇪🇨",
  "Bolivian": "🇧🇴",
  "Paraguayan": "🇵🇾",
  "Uruguayan": "🇺🇾",
  "Chilean": "🇨🇱",
  "Haitian": "🇭🇹",
  "Trinidadian": "🇹🇹",
  "Tobagonian": "🇹🇹",
  "Guyanese": "🇬🇾",
  "Latin": "🌎",
  "Latin American": "🌎",
  "Cajun": "⚜️",
  "Creole": "⚜️",
  "Southern": "🤠",
  "Soul": "🥘",
  "Soul Food": "🥘",
  "Southwestern": "🌵",
  "Hawaiian": "🌺",

  // --- 🇪🇺 EUROPE ---
  "Italian": "🇮🇹",
  "French": "🇫🇷",
  "Spanish": "🇪🇸",
  "German": "🇩🇪",
  "Bavarian": "🥨",
  "Greek": "🇬🇷",
  "Irish": "🇮🇪",
  "British": "🇬🇧",
  "English": "🇬🇧",
  "Scottish": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Polish": "🇵🇱",
  "Russian": "🇷🇺",
  "Ukrainian": "🇺🇦",
  "Portuguese": "🇵🇹",
  "Swiss": "🇨🇭",
  "Austrian": "🇦🇹",
  "Belgian": "🇧🇪",
  "Dutch": "🇳🇱",
  "Swedish": "🇸🇪",
  "Norwegian": "🇳🇴",
  "Danish": "🇩🇰",
  "Scandinavian": "❄️",
  "Nordic": "❄️",
  "Hungarian": "🇭🇺",
  "Czech": "🇨🇿",
  "Romanian": "🇷🇴",
  "Moldovan": "🇲🇩",
  "Serbian": "🇷🇸",
  "Croatian": "🇭🇷",
  "Albanian": "🇦🇱",
  "Balkan": "⛰️",
  "Georgian": "🇬🇪",
  "Armenian": "🇦🇲",
  "Basque": "🇪🇸",
  "Galician": "🇪🇸",
  "Catalan": "🇪🇸",
  "Sardinian": "🇮🇹",
  "Sicilian": "🇮🇹",
  "Tuscan": "🇮🇹",
  "Mediterranean": "🫒",
  "European": "🇪🇺",
  "Eastern European": "🥟",

  // --- 🌏 ASIA ---
  "Chinese": "🇨🇳",
  "Cantonese": "🇨🇳",
  "Sichuan": "🌶️",
  "Szechuan": "🌶️",
  "Hunan": "🌶️",
  "Shanghai": "🇨🇳",
  "Fuzhou": "🇨🇳",
  "Northern Chinese": "🇨🇳",
  "Japanese": "🇯🇵",
  "Korean": "🇰🇷",
  "Indian": "🇮🇳",
  "Thai": "🇹🇭",
  "Vietnamese": "🇻🇳",
  "Filipino": "🇵🇭",
  "Phillipine": "🇵🇭",
  "Malaysian": "🇲🇾",
  "Indonesian": "🇮🇩",
  "Pakistani": "🇵🇰",
  "Bangladeshi": "🇧🇩",
  "Bengladeshi": "🇧🇩",
  "Nepalese": "🇳🇵",
  "Nepali": "🇳🇵",
  "Himalayan": "🏔️",
  "Tibetan": "🏔️",
  "Bhutanese": "🇧🇹",
  "Sri Lankan": "🇱🇰",
  "Taiwanese": "🇹🇼",
  "Burmese": "🇲🇲",
  "Cambodian": "🇰🇭",
  "Singaporean": "🇸🇬",
  "Uzbek": "🇺🇿",
  "Kazakh": "🇰🇿",
  "Tajik": "🇹🇯",
  "Uyghur": "☪️",
  "Central Asian": "🌏",
  "Asian": "🥢",
  "Pan Asian": "🥢",
  "Oriental": "🥢",

  // --- 🐪 MIDDLE EAST ---
  "Lebanese": "🇱🇧",
  "Turkish": "🇹🇷",
  "Israeli": "🇮🇱",
  "Jewish": "✡️",
  "Kosher": "✡️",
  "Persian": "🇮🇷",
  "Iranian": "🇮🇷",
  "Afghan": "🇦🇫",
  "Syrian": "🇸🇾",
  "Yemeni": "🇾🇪",
  "Egyptian": "🇪🇬",
  "Moroccan": "🇲🇦",
  "Algerian": "🇩🇿",
  "Arab": "🇸🇦",
  "Palestinian": "🇵🇸",
  "Middle Eastern": "🥙",
  "Halal": "🕌",
  "Druze": "🥙",
  "Bukharian": "🇺🇿",

  // --- 🌍 AFRICA ---
  "Ethiopian": "🇪🇹",
  "Nigerian": "🇳🇬",
  "Ghanaian": "🇬🇭",
  "Senegalese": "🇸🇳",
  "Somali": "🇸🇴",
  "South African": "🇿🇦",
  "West African": "🌍",
  "East African": "🌍",
  "North African": "🌍",
  "African": "🌍",

  // --- 🇦🇺 OCEANIA ---
  "Australian": "🇦🇺",
  "New Zealand": "🇳🇿",
  
  // --- 🏛️ VENUE TYPES ---
  "Diner": "☕",
  "Bistro": "🍽️",
  "Gastropub": "🍺",
  "Tavern": "🍺",
  "Trattoria": "🇮🇹",
  "Izakaya": "🍶",
  "Teahouse": "🍵",
  "Tea House": "🍵",
  "Food Court": "🏢",
  "Market": "🏪",
  "Street Food": "🥡",
  "Buffet": "🍽️",
  "Catering": "🍽️",
  "Fine Dining": "🤵",
};